name = "FigCLIGen"
uuid = "bc9c4d6b-10c7-430a-9b0c-cd343efcf359"
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
JSON = "0.20, 0.21"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
